In [2]:
import numpy as np

### 문자열 포함되면 int형도 문자열 취급

In [2]:
list1 = [1,2,'test']
array1 = np.array(list1)
print('array1 타입 : ', array1.dtype)

array1 타입 :  <U11


### float형 포함이면 int형도 float 취급

In [3]:
list2 = [1,2,3.0]
array2 = np.array(list2)
print('array2 타입 : ', array2.dtype)

array2 타입 :  float64


<span style="background-color:yellow">array는 데이터값이 모두 같은 타입</span>

### astype : 데이터 타입 변경

In [4]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')

print(array_float, array_float.dtype)

[1. 2. 3.] float64


<span style="background-color:yellow">float - > int 메모리 절약 가능</span>

### reshape : 특정 차원, 크기로 변환

In [19]:
array1 = np.arange(10)
print('array1 : \n', array1, '\n')

array2 = array1.reshape(2,5)
print('array2 : \n',array2, array2.shape, '\n')

array3 = array1.reshape(5,2)
print('array3 : \n',array3, array3.shape, '\n')

array1 : 
 [0 1 2 3 4 5 6 7 8 9] 

array2 : 
 [[0 1 2 3 4]
 [5 6 7 8 9]] (2, 5) 

array3 : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] (5, 2) 



In [22]:
array4 = array1.reshape(-1,5)
print('array4 : \n',array4, array4.shape, '\n')

array4 : 
 [[0 1 2 3 4]
 [5 6 7 8 9]] (2, 5) 



<span style="background-color:yellow">reshape(-1,5)의 -1은 가능한 차원크기로 맞춰줌</span>

### reshape(-1,1) : 3차원을 2차원으로 또는 1차원을 2차원으로 변환

In [36]:
array1 = np.arange(8)
print('array1 : \n', array1.tolist(), '\n')

array3d = array1.reshape(2,2,2)
print('array3d : \n', array3d, '\n')

# 3차원 -> 2차원
array2d = array3d.reshape(-1,1)
print('array2d : \n', array2d.tolist(), '\n')

# 1차원 -> 2차원
array2d2 = array1.reshape(-1,1)
print('array2d2 : \n', array2d2.tolist())

array1 : 
 [0, 1, 2, 3, 4, 5, 6, 7] 

array3d : 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] 

array2d : 
 [[0], [1], [2], [3], [4], [5], [6], [7]] 

array2d2 : 
 [[0], [1], [2], [3], [4], [5], [6], [7]]


<span style="background-color:yellow">array1 : 1차원 ---- array2d, array2d2 : 2차원  <br>차이 확인</span>

### 1차원 인덱싱(indexing)

In [46]:
array1 = np.arange(start=1, stop=10)
print('array1 : \n', array1, '\n')
print(array1[1], array1[-1], '\n')

array1[1] = 0
print(array1)

array1 : 
 [1 2 3 4 5 6 7 8 9] 

2 9 

[1 0 3 4 5 6 7 8 9]


<span style="background-color:yellow">np.arange(start=1, stop=10) 일 때 1~9 까지</span>

### 2차원 인덱싱(indexing)

In [49]:
array1 = np.arange(start=1, stop=10)
array2d = array1.reshape(3,3)
print('array2d : \n', array2d, '\n')

print('(row=0, col=0) = ', array2d[0,0])
print('(row=1, col=0) = ', array2d[1,0])
print('(row=2, col=0) = ', array2d[2,0])
print('(row=0, col=1) = ', array2d[0,1])
print('(row=1, col=1) = ', array2d[1,1])
print('(row=2, col=1) = ', array2d[2,1])
print('(row=0, col=2) = ', array2d[0,2])
print('(row=1, col=2) = ', array2d[1,2])
print('(row=2, col=2) = ', array2d[2,2])

array2d : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

(row=0, col=0) =  1
(row=1, col=0) =  4
(row=2, col=0) =  7
(row=0, col=1) =  2
(row=1, col=1) =  5
(row=2, col=1) =  8
(row=0, col=2) =  3
(row=1, col=2) =  6
(row=2, col=2) =  9


<span style="background-color:yellow">(row=0, col=0) == (axis 0=0, axis 1=0)</span><br>
<span style="background-color:yellow">(row=2, col=1) == (axis 0=2, axis 1=1)</span>

### 1차원 슬라이싱(slicing)

In [53]:
array1 = np.arange(start=1, stop=10)
print(array1[:3])
print(array1[3:])
print(array1[:])

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


<span style="background-color:yellow">[:3]은 인덱스번호 0,1,2</span><br>
<span style="background-color:yellow">[3:]은 인덱스번호 3,4,5,6,7,8</span>

### 2차원 슬라이싱(slicing)

In [63]:
array1 = np.arange(start=1, stop=10)
array2d = array1.reshape(3,3)

print('array2d[1:2, 0:3]:', '\n', array2d[1:2, 0:3], '\n')
print('array2d[1:, 2]:', '\n', array2d[1:, 2], '\n')
print('array2d[1:3, 0:3]:', '\n', array2d[1:3, 0:3], '\n')
print('array2d[:, 0:1]:', '\n', array2d[:, 0:1], '\n')
print('array2d[:, :]:', '\n', array2d[:, :])

array2d[1:2, 0:3]: 
 [[4 5 6]] 

array2d[1:, 2]: 
 [6 9] 

array2d[1:3, 0:3]: 
 [[4 5 6]
 [7 8 9]] 

array2d[:, 0:1]: 
 [[1]
 [4]
 [7]] 

array2d[:, :]: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


<span style="background-color:yellow">인덱싱, 슬라이싱 모두 0번부터 시작인거 헷갈 ㄴㄴ</span>

In [7]:
org_array = np.array([3,1,7,9])
print('원본 행렬 :',org_array, '\n')

sort_array = np.sort(org_array)
print('정렬된 행렬 :',sort_array, '\n')

sort_desc_array = np.sort(org_array)[::-1]
print('내림차순 행렬 :', sort_desc_array)

원본 행렬 : [3 1 7 9] 

정렬된 행렬 : [1 3 7 9] 

내림차순 행렬 : [9 7 3 1]


<span style="background-color:yellow">np.sort() - 오름차순</span><br>
<span style="background-color:yellow">np.sort().[::-1] - 내림차순</span>

In [11]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스 :', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스 : [1 0 3 2]


<span style="background-color:yellow">np.argsort() - 원본 행렬의 인덱스</span><br>
<span style="background-color:yellow">[::1] - 내림차순도 가능</span>

In [14]:
A = np.array([[1,2,3],
              [4,5,6]])

B = np.array([[7,8],
              [9,10],
              [11,12]])
dot_d = np.dot(A,B)
print('행렬 내적 :\n',dot_d)

행렬 내적 :
 [[ 58  64]
 [139 154]]


<span style="background-color:yellow">3x2 2x3 행렬의 내적은 1열*1행 순으로 2x2 내적 행렬 나옴,</span>

In [16]:
A = np.array([[1,2],
              [3,4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬 :\n', transpose_mat)

A의 전치 행렬 :
 [[1 3]
 [2 4]]


<span style="background-color:yellow">전치행렬 - 행과 열 자리 바꾸기</span>